name: ${name}
main: me.brycensranch.BrycensPlayerManager.bukkit.BPMPlugin
version: ${version}
api-version: 1.13
description: ${description}
author: ${author}
commands:
    bpm:
        description: "${name} main command"
        usage: "bpm help"
        permission: ${name}.admin
        permission-message: "You do not have permission to use this command"